export type Country = {
  name: string;
  flag: string;
  dialCode: string;
  phoneRegex: RegExp;
  counties: string[];
};

export const COUNTRIES: Country[] = [
  {
    name: "Kenya",
    flag: "🇰🇪",
    dialCode: "+254",
    phoneRegex: /^(7\d{8}|1\d{8})$/,
    counties: [
      "Mombasa",
      "Kwale",
      "Kilifi",
      "Tana River",
      "Lamu",
      "Taita Taveta",
      "Garissa",
      "Wajir",
      "Mandera",
      "Marsabit",
      "Isiolo",
      "Meru",
      "Tharaka Nithi",
      "Embu",
      "Kitui",
      "Machakos",
      "Makueni",
      "Nyandarua",
      "Nyeri",
      "Kirinyaga",
      "Murang'a",
      "Kiambu",
      "Turkana",
      "West Pokot",
      "Samburu",
      "Trans Nzoia",
      "Uasin Gishu",
      "Elgeyo Marakwet",
      "Nandi",
      "Baringo",
      "Laikipia",
      "Nakuru",
      "Narok",
      "Kajiado",
      "Kericho",
      "Bomet",
      "Kakamega",
      "Vihiga",
      "Bungoma",
      "Busia",
      "Siaya",
      "Kisumu",
      "Homa Bay",
      "Migori",
      "Kisii",
      "Nyamira",
      "Nairobi",
    ],
  },

  {
    name: "Uganda",
    flag: "🇺🇬",
    dialCode: "+256",
    phoneRegex: /^(7\d{8})$/,
    counties: [
      "Kampala",
      "Wakiso",
      "Mukono",
      "Jinja",
      "Mbarara",
      "Gulu",
      "Mbale",
      "Arua",
      "Masaka",
      "Lira",
      "Fort Portal",
      "Hoima",
      "Soroti",
      "Kabale",
    ],
  },

  {
    name: "Tanzania",
    flag: "🇹🇿",
    dialCode: "+255",
    phoneRegex: /^(6\d{8}|7\d{8})$/,
    counties: [
      "Dar es Salaam",
      "Arusha",
      "Mwanza",
      "Dodoma",
      "Mbeya",
      "Morogoro",
      "Zanzibar",
      "Kilimanjaro",
      "Tabora",
      "Shinyanga",
      "Iringa",
      "Kigoma",
      "Geita",
      "Kagera",
      "Katavi",
      "Lindi",
      "Manyara",
      "Mara",
      "Mtwara",
      "Njombe",
      "Pemba North",
      "Pemba South",
      "Pwani",
      "Rukwa",
      "Ruvuma",
      "Simiyu",
      "Singida",
      "Songwe",
      "Tanga",
      "Unguja North",
      "Unguja South",
    ],
  },

  {
    name: "Rwanda",
    flag: "🇷🇼",
    dialCode: "+250",
    phoneRegex: /^(7\d{8})$/,
    counties: [
      "Kigali",
      "Gasabo",
      "Kicukiro",
      "Nyarugenge",
      "Musanze",
      "Rubavu",
      "Huye",
      "Muhanga",
      "Rwamagana",
    ],
  },

  {
    name: "Burundi",
    flag: "🇧🇮",
    dialCode: "+257",
    phoneRegex: /^(6\d{7}|7\d{7})$/,
    counties: [
      "Bujumbura",
      "Gitega",
      "Ngozi",
      "Rumonge",
      "Muyinga",
      "Kayanza",
      "Makamba",
      "Kirundo",
    ],
  },

  {
    name: "South Sudan",
    flag: "🇸🇸",
    dialCode: "+211",
    phoneRegex: /^(9\d{8})$/,
    counties: [
      "Juba",
      "Wau",
      "Malakal",
      "Bor",
      "Yei",
      "Aweil",
      "Bentiu",
      "Torit",
    ],
  },

  {
    name: "Ethiopia",
    flag: "🇪🇹",
    dialCode: "+251",
    phoneRegex: /^(9\d{8})$/,
    counties: [
      "Addis Ababa",
      "Dire Dawa",
      "Mekelle",
      "Bahir Dar",
      "Hawassa",
      "Adama",
      "Jimma",
      "Gondar",
    ],
  },

  {
    name: "Somalia",
    flag: "🇸🇴",
    dialCode: "+252",
    phoneRegex: /^(6\d{8})$/,
    counties: [
      "Mogadishu",
      "Hargeisa",
      "Bosaso",
      "Kismayo",
      "Baidoa",
      "Beledweyne",
      "Garowe",
      "Berbera",
    ],
  },

  {
    name: "Djibouti",
    flag: "🇩🇯",
    dialCode: "+253",
    phoneRegex: /^(7\d{7})$/,
    counties: [
      "Djibouti City",
      "Ali Sabieh",
      "Dikhil",
      "Obock",
      "Tadjourah",
      "Arta",
    ],
  },

  {
    name: "Eritrea",
    flag: "🇪🇷",
    dialCode: "+291",
    phoneRegex: /^(7\d{6})$/,
    counties: [
      "Asmara",
      "Massawa",
      "Keren",
      "Mendefera",
      "Barentu",
      "Assab",
    ],
  },
];
