import React from "react";
import { 
  FileText, 
  AlertCircle, 
  Code,
  Lock
} from "lucide-react";

export default function Terms() {
  return (
    <section  
      id="terms"  
      aria-labelledby="terms-heading"  
      className="scroll-mt-24 border-b border-border bg-background text-foreground"  
    >
      <div className="mx-auto flex w-full max-w-5xl flex-col gap-16 px-6 py-20 sm:px-8 lg:px-10">
        
        {/* Header */}
        <header className="space-y-5">
          <span className="inline-flex items-center px-4 py-2 tracking-[0.18em] uppercase text-sm font-medium text-primary">
            Terms of Service
          </span>

          <h2  
            id="terms-heading"  
            className="font-heading text-3xl font-bold tracking-tight text-foreground sm:text-4xl"  
          >  
            Terms and Conditions  
          </h2>  

          <p className="max-w-3xl text-base leading-8 text-text-body sm:text-lg">  
            Welcome to my professional portfolio and platform. By accessing or using this website, 
            including the integrated AI assistant, blog, and associated services, you agree to comply 
            with and be bound by the following terms and conditions. If you do not agree to these terms, 
            please refrain from using this site.
          </p>  
        </header>  

        {/* 1. Intellectual Property */}  
        <section aria-labelledby="ip-heading" className="space-y-5 border-t border-border pt-10">  
          <div className="flex items-center gap-3">
            <h3
              id="ip-heading"  
              className="font-heading text-2xl font-semibold text-foreground"  
            >  
              Intellectual Property Rights  
            </h3>  
          </div>

          <div className="space-y-4 max-w-3xl text-base leading-8 text-text-body">
            <p>  
              All original content featured on this website—including but not limited to project source code, 
              architectural documentation, UI designs, blog articles, brand assets, images, and graphics—is 
              my personal intellectual property unless explicitly stated otherwise or attributed to open-source 
              licenses.
            </p>  
            <p>  
              You are welcome to explore my public repositories and live implementations for educational 
              purposes. However, duplication, commercial exploitation, or distribution of closed-source material, 
              custom branding, or proprietary backend code without prior written authorization is strictly prohibited.
            </p>  
          </div>
        </section>  

        {/* 2. AI Assistant Disclaimer */}  
        <section aria-labelledby="ai-disclaimer-heading" className="space-y-5 border-t border-border pt-10">  
          <div className="flex items-center gap-3">
            <h3  
              id="ai-disclaimer-heading"  
              className="font-heading text-2xl font-semibold text-foreground"  
            >  
              AI Assistant Disclaimer &amp; Usage  
            </h3>  
          </div>

          <div className="space-y-4 max-w-3xl text-base leading-8 text-text-body">
            <p>  
              The interactive conversational interface on this website is powered by an artificial intelligence 
              assistant utilizing Google&apos;s Gemini Large Language Model (LLM) API. This tool is intended solely 
              for informational, interactive, and contextual demonstration purposes.
            </p>  
            <div className="rounded-lg border border-secondary bg-background p-4 text-sm sm:text-base">
              <p className="font-semibold text-foreground flex items-center gap-2">
                <AlertCircle className="h-4 w-4 text-primary flex-shrink-0" />
                Important Notice regarding AI Output:
              </p>
              <p className="mt-2 text-text-body">
                AI model outputs can fluctuate and may occasionally include inaccurate, incomplete, or hallucinated 
                technical statements. Content generated by the assistant does not constitute official engineering blueprints, 
                binding software consultations, or legal/professional development advice. You assume full responsibility 
                for validating any code snippets, strategies, or technical insights generated by the assistant before 
                production deployment.
              </p>
            </div>
          </div>
        </section>  

        {/* 3. Acceptable Use & Conduct */}  
        <section aria-labelledby="acceptable-use-heading" className="space-y-5 border-t border-border pt-10">  
          <div className="flex items-center gap-3">
            <h3  
              id="acceptable-use-heading"  
              className="font-heading text-2xl font-semibold text-foreground"  
            >  
              Acceptable Use Policy  
            </h3>  
          </div>

          <p className="text-base leading-8 text-text-body max-w-3xl">  
            To preserve the availability, performance, and security of this platform for all visitors, 
            you agree not to engage in any of the following prohibited behaviors:  
          </p>  

          <div className="grid gap-6 sm:grid-cols-2">
            <div className="space-y-2">
              <div className="flex items-center gap-4">
               <div
                aria-hidden="true"
                className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full border border-border bg-background"
               >
                <Code
                  size={22}
                  className=" text-primary"
                  />
                </div>
                <h4 className="font-heading font-medium text-foreground">API and Form Abuse</h4>
              </div>
              <p className="text-base leading-8 text-text-body max-w-3xl">
                You must not execute programmatic script injections, automate spam submissions via the contact form, 
                or consciously prompt the AI assistant to perform heavy-resource exhaustion vectors.
              </p>
            </div>

            <div className="space-y-2">
              <div className="flex items-center gap-4">
               <div
                 aria-hidden="true"
                 className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full border border-border bg-background"
                >
                <Lock
                  size={22}
                  className="text-primary"
                />
                </div>
                <h4 className="font-heading font-medium text-foreground">Unauthorized Access</h4>
              </div>
              <p className="text-base leading-8 text-text-body max-w-3xl">
                Any deliberate attempts to bypass rate limits, probe security endpoints, scrape content database paths, 
                or force access into secure Admin panels or backend systems will be immediately restricted and reported.
              </p>
            </div>
          </div>
        </section>  

        {/* 4. Limitation of Liability */}  
        <section aria-labelledby="liability-heading" className="space-y-5 border-t border-border pt-10">  
          <div className="flex items-center gap-3">
            <h3  
              id="liability-heading"  
              className="font-heading text-2xl font-semibold text-foreground"  
            >  
              Limitation of Liability  
            </h3>  
          </div>

          <div className="space-y-4 max-w-3xl text-base leading-8 text-text-body">
            <p>  
              This website and all included text, assets, code samples, and operational features are provided on 
              an &quot;as-is&quot; and &quot;as-available&quot; basis without warranties of any kind, whether explicit 
              or implied. 
            </p>  
            <p>  
              Under no circumstances shall I be held liable for any direct, indirect, incidental, or consequential 
              damages, operational losses, data discrepancies, system disruptions, or security issues arising from your 
              reliance on my blog, external hyperlinks, live project portfolio deployments, or third-party cloud infrastructure.
            </p>  
          </div>
        </section>  

        {/* 5. Governing Law */}  
        <section aria-labelledby="governing-heading" className="space-y-5 border-t border-border pt-10">  
          <div className="flex items-center gap-3">
            <h3  
              id="governing-heading"  
              className="font-heading text-2xl font-semibold text-foreground"  
            >  
              Governing Law  
          </h3>  
          </div>

          <p className="max-w-3xl text-base leading-8 text-text-body">  
            These terms and conditions are governed by and construed in accordance with the relevant local and international 
            data security frameworks and electronic transaction standards. Any disputes or enforcement initiatives 
            pertaining to platform vulnerability exploitation or unauthorized structural abuse will be addressed within 
            the respective competent legal jurisdictions.
          </p>  
        </section>  

        {/* Last Updated Footer */}  
        <footer className="border-t border-border pt-8 mt-4">  
          <p className="text-sm leading-7 text-foreground-muted">  
            <strong>Last reviewed:</strong> June 2026  
          </p>  

          <p className="mt-2 text-sm leading-7 text-foreground-muted">  
            These Terms and Conditions may be modified dynamically to account for newly integrated features, updated security protocols, 
            or changing architectural compliance metrics.
          </p>  
        </footer>  
      </div>  
    </section>
  );
}

